training:
  lr: 1e-4
  weight-decay: 1e-5
  bs: 128
  workers: 0
  scheduler: 'steplr'
  gamma: 0.5
  step-size: 250
  q_size: 2048
  T: 0.07
  M: 0.995
  lambda: 0.5

model:
  h_dim: 128
  o_dim: 128
  depth: 2
  dropout: 0.3